### ISSUE TITLE
Wrapper for easy usage with NodeRED

### ISSUE THREAD

**Issue by yankee42** [Apollon77/daikin-controller#105]
I just want to let you know that I wrote a tiny wrapper around this library to make it easier to use it together with NodeRED. In case you want to link it: https://flows.nodered.org/node/node-red-contrib-daikin-ac. It is my first NodeRED-Code. Actually it is the first time I write something for NodeJS, so it probably could be a lot better, but it works.

Also thank you a lot for writing and maintaining this library.

**Comment by Apollon77** [comment]
sure
