### ISSUE TITLE
Update stops after connection failure

### ISSUE THREAD

**Issue by WolfspiritM** [Apollon77/daikin-controller#11]
Hi,

If the daikin device loses connection (for example the AP or some other network component restarts) I noticed that the update interval is not continuing.

I'm using this with the iobroker adapter and after upgrading my Switch firmware (which resulted in a restart) this morning the outside and indoor Temperature (and everything else) didn't update anymore until I restarted the adapter.

As the adapter is using setUpdate I assume there is some issue in this lib that in case of an error is not restarting the timeout, but I wasn't able to figure it out yet. Maybe a more reliable way would be using setInterval instead?

**Comment by Apollon77** [comment]
The Adapter Log from such an error case would be really helpful!

setInterval is no good option when working with external asynchronous communication

**Comment by Apollon77** [comment]
Also great would be when you try to reproduce it with having debug loglevel enabled in adapter

**Comment by Apollon77** [comment]
Great! Indeed it is also the lib ;-) with this Infos it should be easy to track it down. Thank you!

**Comment by Apollon77** [comment]
So thought about it.

The Lib tries to get some basic data from the device as "Initialization" and if this do not work then the Library do not "start" at all -  and this is understandable becase the IP could also be wrong or such and then queriing invalid stuff is stupid.

So what I could do it add more checks in adapter to catch this case and then stop the adapter because also here this case can be invalid IP and other data in configuration. This would mean that in this case adapter would be restarted some times (when the outage is longer) and sometime it will be disabled completely by js-controller because of these continous restarts ...

What do you think about that?

**Comment by WolfspiritM** [comment]
In a case where the adapter freshly starts and has no information about the endpoint I think the best option would be to just retry the initializing every now and then (possibly based on the poll interval) until it is successful (I can think of cases where the network might not be available if the device just restarted). I think that can be catched fully in the adapter where the new instance of DaikinAC is created.

The main issue however is that the running Instance of the adapter crashes if a connection fails cause currentACControlInfo is null in this case according the the Exception I posted.
https://github.com/Apollon77/ioBroker.daikin/blob/master/daikin.js#L386

I don't think that the lib should set currentACControlInfo (and the others like currentCommonBasicInfo) in case of an error at all:
https://github.com/Apollon77/daikin-controller/blob/master/lib/DaikinAC.js#L113

It might be as simple as:
``` js
if(!err) self.currentACControlInfo = daikinResponse;
```

**Comment by Apollon77** [comment]
> In a case where the adapter freshly starts and has no information about the endpoint I think the best option would be to just retry the initializing every now and then (possibly based on the poll interval) until it is successful (I can think of cases where the network might not be available if the device just restarted). I think that can be catched fully in the adapter where the new instance of DaikinAC is created.

I need to think about that ... having adapter run without a connection and retry from time to time or end the adapter process to get automatically restarted by js-controller after 30s ....

>The main issue however is that the running Instance of the adapter crashes if a connection fails cause currentACControlInfo is null in this case according the the Exception I posted.
https://github.com/Apollon77/ioBroker.daikin/blob/master/daikin.js#L386
I don't think that the lib should set currentACControlInfo (and the others like currentCommonBasicInfo) in case of an error at all:
https://github.com/Apollon77/daikin-controller/blob/master/lib/DaikinAC.js#L113

Correct, I will fix this!

**Comment by Apollon77** [comment]
Please check GitHub version

**Comment by Apollon77** [comment]
Stop, one more fix later today

**Comment by Apollon77** [comment]
try 1.1.3 from GitHub please
