### ISSUE TITLE
PIR Sensor info request

### ISSUE THREAD

**Issue by william-bohannan** [Apollon77/daikin-controller#110]
Great work!  Please advise if possible to read data from the PIR sensor on the unit, as this would be extremely handy in node-red as i can then detect when there was last movement in a room?

Just for info, i have successfully connected to the Daikin units via node-red, below is the model info i am running (from node red!):
model: 10F9
type: N
region: eu
adapterVersion: 1_2_54
pv 3
cpv 3

**Comment by Apollon77** [comment]
The App do not show it and noone ever saw it somewhere, so most likely not

**Comment by william-bohannan** [comment]
that is a real shame, as it would make the rooms not need extra 3rd party sensors (use the one PIR sensor for everything in the room).  do you have a contact at daikin and i can contact their support to try and get some information on it?

**Comment by Apollon77** [comment]
Nope, no contact and no infos provided, all is reverse engineered. Do not expect too much from them
