### ISSUE TITLE
Does 'set and get_remote_method for increasing notice_sync_int' work for increasing update interval/ sync rate? 

### ISSUE THREAD

**Issue by bjornstevens** [Apollon77/daikin-controller#111]
**Is your feature request related to a problem? Please describe.**
In the /common/get_remote_method page i see the notice_sync_int, can this be changed via this, and if so can it be added to this controller. (I did see it on to-do but this also acts as a question).

**Describe the solution you'd like**
I would like this to be able to increase the update (notice_sync_int) rate of the unit info (in my case i want to be able to monitor the cmpfreq more often)

**Describe alternatives you've considered**
I am not a pro at all, I really don't know what do and don't want to break things.

**Additional context**
State now (/common/get_remote_method):
![afbeelding](https://user-images.githubusercontent.com/23235234/121822769-2192c580-cca1-11eb-8a84-75ae51067ef3.png)
I guess the update interval right now is 60 seconds. But also wonder what would be the lowest (<5 seconds?)

**Comment by Apollon77** [comment]
The issue is that from all we know is how a "get" looks like ...  for set someone need to experiment and collect information on how to set the data

**Comment by bjornstevens** [comment]
Is there not a dev available, or a (well described) API? I always seem to get stuck in the hundreds of manuals of Daikin..

**Comment by Apollon77** [comment]
Nothing official exists ... anything we know is reverse engineered .... sorry. And "dev available" means what?  :-) I will try to find time somewhen to see if my device supports that and what happens ... so I can also only try it out.

**Comment by bjornstevens** [comment]
Dev available, like someone that knows someone that works at Daikin departement that knows this stuff 😆. Looking forward to what you can find 😄.

Just more about that 'dev' thing. Once I had an issue were i wanted to look into my solar API. There weren't online documents, but they sent me their internal API documentation with like everything in it. Was hoping something like that existed also for Daikin 😛
