### ISSUE TITLE
Special Modes: unable to set (using Emura 2)

### ISSUE THREAD

**Issue by PeterEIER** [Apollon77/daikin-controller#12]
I am unable to set "POWERFUL" mode although the airco is ON and all the other settings i.e mode are working flawlessly. See respons below, in bold the "set_special_mode"... suggestions are welcome!

Call GET http://192.168.0.43/common/basic_info with undefined
{"type":"aircon","region":"eu","dst":true,"adapterVersion":"3_3_1","power":true,"error":0,"location":0,"name":"Emura Woonkamer","icon":1,"method":"home only","port":30050,"id":"","password":"","lpwFlag":0,"adapterKind":2,"pv":2,"cpv":2,"cpvMinor":0,"led":true,"enSetzone":1,"macAddress":"784B8799BF43","adapterMode":"run","enHol":0,"groupName":"","enGroup":0}
Call GET http://192.168.0.43/aircon/get_control_info with undefined
{"power":true,"mode":3,"specialMode":"","targetTemperature":23,"targetHumidity":0,"targetTemperatureMode1":23,"targetTemperatureMode2":"M","targetTemperatureMode3":23,"targetTemperatureMode4":21,"targetTemperatureMode5":21,"targetTemperatureMode7":23,"targetHumidityMode1":0,"targetHumidityMode2":0,"targetHumidityMode3":0,"targetHumidityMode4":0,"targetHumidityMode5":0,"targetHumidityMode7":0,"targetHumidityModeH":50,"modeB":3,"targetTemperatureB":23,"targetHumidityB":0,"error":255,"fanRate":"B","fanDirection":3,"fanRateB":"B","fanDirectionB":3,"fanRateMode1":"A","fanRateMode2":"A","fanRateMode3":"B","fanRateMode4":"A","fanRateMode5":"A","fanRateMode6":"A","fanRateMode7":"A","fanRateModeH":5,"fanDirectionMode1":3,"fanDirectionMode2":3,"fanDirectionMode3":3,"fanDirectionMode4":3,"fanDirectionMode5":3,"fanDirectionMode6":3,"fanDirectionMode7":3,"fanDirectionModeH":0}
**Call POST http://192.168.0.43/aircon/set_special_mode with {"set_spmode":1,"spmode_kind":1}
{"adv":""}**

**Comment by Apollon77** [comment]
You can set POWERFUL mode successfully via the Daikin app?

**Comment by PeterEIER** [comment]
No I can not as the POWERFUL button is not showing in the Daikin app, I can however set it from the IR remote and when I do so I see POWERFUL indicated in the Daikin app. When set with the IR remote this is the response from the airco:

Call GET http://192.168.0.43/aircon/get_control_info with undefined
{"power":true,"mode":3,**"specialMode":"2"**,"targetTemperature":21,"targetHumidity":0,"targetTemperatureMode1":23,"targetTemperatureMode2":"M","targetTemperatureMode3":21,"targetTemperatureMode4":21,"targetTemperatureMode5":21,"targetTemperatureMode7":23,"targetHumidityMode1":0,"targetHumidityMode2":0,"targetHumidityMode3":0,"targetHumidityMode4":0,"targetHumidityMode5":0,"targetHumidityMode7":0,"targetHumidityModeH":50,"modeB":3,"targetTemperatureB":21,"targetHumidityB":0,"error":255,"fanRate":"A","fanDirection":3,"fanRateB":"A","fanDirectionB":3,"fanRateMode1":"A","fanRateMode2":"A","fanRateMode3":"A","fanRateMode4":"A","fanRateMode5":"A","fanRateMode6":"A","fanRateMode7":"A","fanRateModeH":5,"fanDirectionMode1":3,"fanDirectionMode2":3,"fanDirectionMode3":3,"fanDirectionMode4":3,"fanDirectionMode5":3,"fanDirectionMode6":3,"fanDirectionMode7":3,"fanDirectionModeH":0}

Well I guess that my WiFi adapter/firmware does not support the POWERFUL setting... what do you think?

**Comment by Apollon77** [comment]
seems so :-(
