### ISSUE TITLE
setACSpecialMode disable the updateInterval

### ISSUE THREAD

**Issue by luigidragone96** [Apollon77/daikin-controller#120]
Hi,
I encountered a bug using the setACSpecialMode function.
When the setACSpecialMode method is invoked, the autoupdate system (updateInterval) turns off.

The this.clearUpdateTimeout() method is called in the setACSpecialMode function but the self.initUpdateTimeout() method is never called after the ACSpecialMode end.

As workaround you need to manually reactivate the updateInterval after setACSpecialMode has finished.

**Comment by Apollon77** [comment]
thank you
