### ISSUE TITLE
control Daikin Perfera 

### ISSUE THREAD

**Issue by davideser** [Apollon77/daikin-controller#133]
Hi good Sunday at everybody,  The configuration for my home is with Raspberry pi with Homebridge, I used homebridge for connect, Btcino living now, some Tuya devices and LG Tv's, Now I can't connect my Daikin air conditioning with Homekit or Homebridge. I can only control them via their official app. I preferred to connect them to homekit to have everything in one app.

My is  Daikin Condizionatore 2 x FTXM25R 2MXM40N Dual Split Perfera Gas R-32 Bluevolution 9+9 WiFi	.

Thanks for any reply.

**Comment by Apollon77** [comment]
WHich WLAN Adapter is installed in the device?

**Comment by davideser** [comment]
I have not bought. i think it has an internal wifi card.

**Comment by Apollon77** [comment]
YOu should see that info in the Daikin App, but without knowing that I can not tell you how it works and would need to close it

**Comment by Apollon77** [comment]
Closed because?

**Comment by davideser** [comment]
I closed because the answers given were not helpful.  Daikin App does not allow for external integration, nor does it provide APIs.

I spent a lot of time figuring out how to connect it, but it doesn't seem to work.  If anyone has any solution.

**Comment by Apollon77** [comment]
The only question was to provide ths info which WLAN adapter is in the device and the Daikin app whre you have added the device normally provides this information. because if you use the Daikin App in your local network then it needs to have a wifi adapter - if you only use your IR Remote control then ... ok I can not help

**Comment by davideser** [comment]
My Daikin devices working with app very good, but I don't find way to connect to homebridge .. and also homeassistant.

**Comment by Apollon77** [comment]
Ok, what you expect from me? Yes this is a library and e.g. homebridge or iobroker could use this library to build something ... but we already know that there are TWO types of devices from Daikin - some support direct local control and some only work via clpud connection ... To know how your device can be controlled we need to know Which Wifi adapter is integrated. Unless you can tell me what wifi adapter is in your device I can not point you or anyone else into a direction on hw to control it aside the app ...

**Comment by davideser** [comment]
I think from cloud, at this point.

**Comment by Apollon77** [comment]
Did you created an accout with email and password to use the device? Then yes, likely cloud

**Comment by davideser** [comment]
Yes
