### ISSUE TITLE
Some commands not working since firmware update

### ISSUE THREAD

**Issue by crunchy59** [Apollon77/daikin-controller#14]
Hello, just for inforamtion, since few days some commands not working, because there is a new firmware update.

**Comment by Apollon77** [comment]
Details please ... What exactly is not working?
For me anything works as usual also with 3.3.6 ... do you restarted the instances?

**Comment by crunchy59** [comment]
Excuse for my english, but:
In th app store there is a new version of app, with new firmware and (perhaps new api) now for exemple my BRP069A4X controler as a new firmware 1.2.51. and now only poweroff and poweron works.

C.

**Comment by Apollon77** [comment]
my controller has firmware 3.3.6 ... so no idea what is this for a controller. :-(

As said: Please enable debug loglevel for the instance (Instanzen -> Expertenmodus -> column log stufe) do actions and post log please

**Comment by Apollon77** [comment]
Ps: did you tried using the „GET mode for older firmwares“?

**Comment by crunchy59** [comment]
Hello,
There are 2 MB revison, older with 3.3.X firmware and newer with 1.2X firmware.
You can close the case. Because after several tests, it's seems to be my mistakes

Thanks again.

C.

**Comment by Apollon77** [comment]
So anything works again for you?
