### ISSUE TITLE
Improve handling of EHOSTUNREACH

### ISSUE THREAD

**Issue by theimo1221** [Apollon77/daikin-controller#177]
**Is your feature request related to a problem? Please describe.**
Sometimes the Wifi Adapter drop the connection. Thus resulting in a response of `EHOSTUNREACH` while e.g. trying to set new control info

**Describe the solution you'd like**
In my opinion the perfect solution would consist of two things:

1. An option for DaikinAC to automatically try a reconnect on `EHOSTUNREACH` errors.
2. Firing a CB to allow the consuming application to try reestablish connection (e.g. by restarting device, force reconnect from the router side, etc.)

**Additional context**
Atleast in my Asus Mesh Network some connections drop from time to time

**Comment by Apollon77** [comment]
The next version will return the original error with adjusted message (to stay backward compatible) so err.code can be used to check on EHOSTUNREACH
