### ISSUE TITLE
daikin-controller via NODE-RED

### ISSUE THREAD

**Issue by ivanovlk** [Apollon77/daikin-controller#19]
Hi there :)

Is it possible to use daikin-controller via NODE-RED ??
if yes , is there an example or something ?! :)

Thanks

**Comment by Apollon77** [comment]
I have no idea, I think someone (TM) would need to develop a node-red plugin that is using it.
I have no experience and no time for that sorry

**Comment by ivanovlk** [comment]
Hi Apollon77,  I found a solution and maybe it will be useful to paste it here.

First in node-red /data/settings.js

append lines:

    functionGlobalContext: {
        DaikinAC:require("daikin-controller")
    },

After that in Node-red a function node is created with something similar to :

var DaikinAC = global.get('DaikinAC');

var options = {'logger': console.log}; // optional logger method to get debug logging

var daikin = new DaikinAC.DaikinAC('192.168.0.XXX', options, function(err) {
    
    if( (msg.payload.toString() == "1") || (msg.payload.toString() == "0")) { //If input if function is On or Off

        daikin.getACControlInfo(function(err) {

            var vals = 
            {    
                'power': (msg.payload.toString() == "1"),
                'mode': 7,
                'fanRate': "A",
                'targetTemperature': daikin.currentACControlInfo.targetTemperature 
            };

            daikin.setACControlInfo(vals, function(err, response) {

                daikin.getACControlInfo(function(err)
                {
                    if (daikin.currentACControlInfo.power === true)
                    node.send([{payload: daikin.currentACControlInfo.power.toString()},{payload: "on"},{payload: "start"}])     // Send to next node one msg for each output of function node
                    else
                    node.send([{payload: daikin.currentACControlInfo.power.toString()},{payload: "off"},{payload: "stop"}])     // 3rd message is used for "Auto-off" timer :)
                });   

            });
        }.bind( {msg: msg} ));
    }
    
}.bind({msg: msg}));

**Comment by bolfox** [comment]
Hi ivanovlk,

Can you share your flow?

Tnx

**Comment by ivanovlk** [comment]
Hi bolfox,

Here it is:
[flows.txt](https://github.com/Apollon77/daikin-controller/files/3410562/flows.txt)
