### ISSUE TITLE
Does anybody know how to interpret the data coming back from getACWeekPower

### ISSUE THREAD

**Issue by Mikee1234K** [Apollon77/daikin-controller#200]
I get data from my 2 Daikin ACs, if I inject the node. I can get the weekly, weekly extended etc. What I was hoping for is getting the usage in KWh per day or week or year, as you can in the app. But the numbers coming back do not make sense to me..
This is a example for ACWeekPower, the only one making sense is the todayRuntime... obviously 0 mins for today. Apart from that scratching my head...

![image](https://user-images.githubusercontent.com/72687610/204566982-f8b73da9-6536-4550-b1a3-3c52dcc7b5ac.png)

**Comment by Apollon77** [comment]
The best idea you have is to open the Daikin Controller App and look at the same time at the values ... then you should be able to see how the app displays them and you could be able to match them.

Maybe also these infos that were collected some time ago might help?
https://github.com/Apollon77/daikin-control/blob/master/README_updated.md#airconget_day_power_ex
