### ISSUE TITLE
Wrong Parameters in request: ret=PARAM NG

### ISSUE THREAD

**Issue by fischmir** [Apollon77/daikin-controller#24]
Hallo,

ich nutze den Adapter auch, aber meine Geräte reagieren etwas zickig. Der abgesetzte Paramtersatz passt wohl nicht.

`
daikin.0 | 2019-08-23 09:39:46.333 | debug | system.adapter.admin.2: logging true
-- | -- | -- | --
daikin.0 | 2019-08-23 09:39:45.262 | error | Error updating data: Wrong Parameters in request: ret=PARAM NG
daikin.0 | 2019-08-23 09:39:45.262 | debug | reset power
daikin.0 | 2019-08-23 09:39:45.261 | error | change values failed: Wrong Parameters in request: ret=PARAM NG
daikin.0 | 2019-08-23 09:39:45.261 | debug | change values:  {"power":false,"mode":0,"specialMode":"","targetTemperature":18,"targetHumidity":0,"targetTemperatureMode1":18,"targetTemperatureMode2":"M","targetTemperatureMode3":21,"targetTemperatu
daikin.0 | 2019-08-23 09:39:45.259 | debug | start update timeout
daikin.0 | 2019-08-23 09:39:45.258 | debug | {"power":false,"mode":0,"specialMode":"","targetTemperature":18,"targetHumidity":0,"targetTemperatureMode1":18,"targetTemperatureMode2":"M","targetTemperatureMode3":21,"targetTemperatureMode4":25,"ta
daikin.0 | 2019-08-23 09:39:45.141 | debug | Call GET http://192.168.178.105/aircon/get_control_info with undefined
daikin.0 | 2019-08-23 09:39:45.140 | debug | {}
daikin.0 | 2019-08-23 09:39:45.018 | debug | Call POST http://192.168.178.105/aircon/set_control_info with {"pow":1,"mode":0,"stemp":"18.0","shum":0,"f_rate":"B","f_dir":3}
daikin.0 | 2019-08-23 09:39:45.013 | debug | change power to true
daikin.0 | 2019-08-23 09:39:44.893 | debug | Call GET http://192.168.178.105/aircon/get_control_info with undefined
daikin.0 | 2019-08-23 09:39:44.892 | debug | clear update timeout
daikin.0 | 2019-08-23 09:39:44.889 | debug | Send 1 changes: {"power":true}
daikin.0 | 2019-08-23 09:39:43.884 | debug | stateChange daikin.0.control.power  {"val":true,"ack":false,"ts":1566545983881,"q":0,"from":"system.adapter.admin.2","user":"system.user.admin","lc":1566545983881}

`

Ich habe hier eine API gefunden:

https://github.com/ael-code/daikin-control

...und die folgenden Befehle funktionieren auch.

http://192.168.178.105/aircon/set_control_info?pow=0&mode=1&stemp=18&shum=0&f_rate=B&f_dir=3
--> ausschalten

http://192.168.178.105/aircon/set_control_info?pow=1&mode=1&stemp=18&shum=0&f_rate=B&f_dir=3
--> anschalten

Verwendet der Adapter die gleichen Befehle? 

Grüße
Christian

**Comment by Apollon77** [comment]
The log lines are cutted. Please do not copy from admin but from logfile on disk (logfile is in log directory in iobroker directory.

**Comment by Apollon77** [comment]
And what device and which wlan adapter is it?

**Comment by fischmir** [comment]
This was important:

Important: Type "B" Wifi adapters from Daikin (firmware 1.4.x, e.g. BRP069Bxx) also were reported to work but need to use the special option "useGetToPost" in the options!

Sorry! Now it worked.

**Comment by BlackTigga** [comment]
If needed please reopen this Issue.

Issue discussion is linked to this thread:
[https://forum.iobroker.net/topic/46736/daikin-klimaanlage-an-ausschalten/22?_=1628163553188](url)

Attached is the LogFile as requested and sequence of exact activities for generation of this error:

-	2021-08-05 14:09:26.265  Start Iobroker adapter
-	2021-08-05 14:09:48.249  switch on AC via VIS Icon Toggle in mode: 3:COLD  
-	2021-08-05 14:10:21.341  switch to mode 2:DEHUMDID (ohne Probleme) 
-	2021-08-05 14:10:55.089  switch to mode 4:HOT (no error) 
-	2021-08-05 14:11:25.495  switch to mode 3:COLD (no error) 
-	2021-08-05 14:11:59.794  switch to mode 6:FAN (no error) 
-	2021-08-05 14:12:31.542  switch to mode 3:COLD (**error** 2021-08-05 14:12:31.929) 
-	2021-08-05 14:12:49.786  switch to mode 4:HOT (**error** 2021-08-05 14:12:50.132) 
-	2021-08-05 14:13:10.928  switch to mode 3:COLD **via DAIKIN Andoird App** (no error) 
-	2021-08-05 14:13:34.734  switch off via VIS Icon Toggle    

[Log File.txt](https://github.com/Apollon77/daikin-controller/files/6940015/Log.File.txt)
