### ISSUE TITLE
Daikin Stylish airco FTXA20AW

### ISSUE THREAD

**Issue by joydashy** [Apollon77/daikin-controller#5]
Any idea if this should be compatible with the newer "Daikin Stylish airco FTXA20AW" unit? I don't see it mentioned in the list, and no idea how to find out!

**Comment by joydashy** [comment]
Thanks for the superfast reply. Seeing they have been faithful to their API, likely this one should work then?

I just checked the manual, it mentions the Daikin App and compatibility with IFTTT, seems like it should work then, or could be modified to work if needed.

**Comment by Apollon77** [comment]
should work :-)
could be modified too, but the challenge would then to re-engenieer what the app sends out

**Comment by Apollon77** [comment]
Please give feedback

**Comment by joydashy** [comment]
Thanks, I will certainly let you know my findings.
