### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by DIY-Blub** [Apollon77/daikin-controller#51]
Hallo Apollon,
kannst du die config-Dateien von dependabot (npm und yarn) & greenkeeper (sinon und nock) so abändern das Version 6 (Version 8 und 10 sind ja fehlerfrei) nicht mehr überprüft wird? Dieses "Build failing" in der Readme wirkte auch auf mich anfangs etwas komisch, dadurch konnte man potenziell interessierte Personen abschrecken.
Überlegs dir :) .... PS: ist noch zu früh für Englisch ;)
SG, Blub
Note: if I am wrong and you are not German, then I am sorry. Of course we'll stick with English.

**Comment by Apollon77** [comment]
Steht auf der Aktualiiserungsliste ... kommt bald dran. Sind zu viele Projekte geworden ;-)

**Comment by Apollon77** [comment]
thank you
