### ISSUE TITLE
tcpdump of daikin.setACControlInfo() in action ?

### ISSUE THREAD

**Issue by prynhart** [Apollon77/daikin-controller#58]
I've got a newer Daikin Controller which only listens on HTTPS (BRP072C42) but the underlying API appears to be the same (see https://community.home-assistant.io/t/daikin-brp072c42-wifi-custom-component/126981).

I'm just wanting to be able to send basic commands at this stage - and I'm trying to use Apollon77/daikin-controller to see the underlying GET and POST requests.

To do this, I've pointed to a "fake Daikin" non HTTPS endpoint (because my Daikin only listens on HTTPS!) and undertaken a packet trace to give me an idea of what I need to send.  (The "fake Daikin" is just a FreeBSD box with httpd - but it gives me enough to be able to see the communications needed.)

On my home network, my FreeBSD box is 192.168.1.3 and my Daikin is 192.168.1.37.  As an example, from initialisation of DaikinAC() I can see (using tcpdump):

```
GET /aircon/get_control_info HTTP/1.1
Content-Type: text/plain
User-Agent: DaikinOnlineController/2.4.2 CFNetwork/978.0.7 Darwin/18.6.0
Accept: */*
Accept-Language: de-de
Accept-Encoding: gzip, deflate
Content-Length: 0
Host: 192.168.1.3
Connection: close
```

which I can then turn into a Curl Request (for my real but HTTPS Daikin) as follows:

```
curl --insecure -H "X-Daikin-uuid: d53b108a0e5e4fb5ab94a343b7d4b74a" "https://192.168.1.37/aircon/get_control_info"
ret=OK,pow=0,mode=4,adv=,stemp=20.0,shum=0,dt1=25.0,dt2=M,dt3=25.0,dt4=20.0,dt5=20.0,dt7=25.0,dh1=0,dh2=50,dh3=0,dh4=0,dh5=0,dh7=0,dhh=50,b_mode=4,b_stemp=20.0,b_shum=0,alert=255,f_rate=B,b_f_rate=B,dfr1=A,dfr2=A,dfr3=B,dfr4=B,dfr5=B,dfr6=A,dfr7=A,dfrh=A,f_dir=0,b_f_dir=0,dfd1=0,dfd2=0,dfd3=3,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0
```

Where I'm coming unstuck is that I don't know the data/string/JSON (?) to make use of the /aircon/set_control_info endpoint.  I've tried looking through the source of Apollon77/daikin-controller - but I'm finding the "human readable" enum types difficult to translate back into what's expected for a simple curl command.

The very first thing I'd like to be able to do is just turn the unit on and off (i.e. somehow send "pow=1").  Would it please be possible for someone to send the raw POST needed for this as an example ?  Because mine is HTTPS only it will be using the newer API - i.e. not the "GET POST" combination.

With Thanks in Advance,

Patrick

**Comment by Apollon77** [comment]
more details for protocol can be found at https://github.com/ael-code/daikin-control

Sorry I have currently no time to provide such an example

**Comment by prynhart** [comment]
Just for others who might stumble upon this - here's a working example:

# curl --insecure -H "X-Daikin-uuid: d53b108a0e5e4fb5ab94a343b7d4b74a" "https://IP_OF_DEVICE/aircon/set_control_info?pow=1&mode=4&stemp=22&shum=0&f_rate=A"
ret=OK,adv=

Note the GET (as opposed to POST which is perhaps a bit more like you'd expect).

I found this page usual to explain the various arguments (in simple terms): https://www.revk.uk/2019/03/daikin-air-con-wifi-control.html
