### ISSUE TITLE
Error handling - DaikinACRequest.js - restClient.get

### ISSUE THREAD

**Issue by PeterEIER** [Apollon77/daikin-controller#6]
I had this issue that my application crashed when I did sent a control command to the airco which was for some reason not connected anymore.

Made changes to DaikinACRequest.js to solve this issue for my application. Have a look, I might makes sense to add it also.

**replaced (line 214):**
`this.restClient.get(url, data, callback);`

**with this:** 
`this.restClient.get(url, data, callback, function () {`
    	`// dummy action which is not executed...`
        `console.log('Request was successfull');`
   ` }).on('error', function (err) {`
    	`console.log('Error, something went wrong on the request:', err.request.options);`
   ` });`

As you can see I added error handling conform to the node-rest-client readme.md.

**Comment by Apollon77** [comment]
What exactly was the error you received before the fix?

**Comment by PeterEIER** [comment]
`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect EHOSTUNREACH 192.168.0.200:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
`

**Comment by Apollon77** [comment]
ok, thank you, will check and fix later today

**Comment by Apollon77** [comment]
Aaahh it seems I need to subscribe to the error event of each single event ... I subscribed to the restClient instance ... :-)

**Comment by Apollon77** [comment]
1.1.2 is available on npm. Please have a try :-)

**Comment by PeterEIER** [comment]
v1.1.2 tested, problem fixed. Thx.

**Comment by Apollon77** [comment]
Thank you
