### ISSUE TITLE
Question - support for the new type B (BRP069Bxx) WiFi adapter

### ISSUE THREAD

**Issue by PeterEIER** [Apollon77/daikin-controller#7]
I am using this library in my own app and it seems that the new Daikin type B WiFi adapter handles POST commands differently (compared to the type A (BRP069Axx)). As a result users of the type B adapter cannot control their airco, the GET command however works fine.

I came across a fora post (https://forum.iobroker.net/viewtopic.php?f=36&t=5896&start=40) were the same issue is discussed by you... it seems from these posts that the issue is not with the command itself but more how the POST command is sent to the airco.

**My question:** did you looked into the type B WiFi adapter issue? Any idea if it can be fixed easily?

**Comment by Apollon77** [comment]
The POST/GET thing was from my knowledge more that "older" Wifi adapters did things different then the "newer" ones ... B oder then A ? Don't know ... when I remember correctly it was also about the firmware versions and then "B" do not get current firmware, but A does ... ?!

So I added a special option, described in README.md:

>Additionally you can set the special flag useGetToPost for older Firmwares of the Daikin-WLAN-Interfaces (<1.4) that only supported HTTP GET also to set data. So if you get errors using it then you try if it works better with this flag. 

From my knowledge - especially refering to the ioBroker Forum post - this was the fix there.

Or do you see more needs?

**Comment by PeterEIER** [comment]
Hi Ingo,

Yes I am aware of the POST/GET thing, and yes I know there is a switch in your software (DaikinACRequest.js).

The type B adapter is the newest Daikin WiFi adapter, it was introduced by Daikin a couple of months ago. All of my users with this type B adapter (actually everyone with a 2018 model airco) have this problem, none of them is offered a firmware upgrade although the firmware in these new type B adapters is 1.2.48. So my guess is that the new adapters use a different firmware with different a numbering scheme. So yes, you remembered correctly and I missed that the fix was use GET iso POST.

Well if this fixes the problem then there is of course no need to change/add something to your code I will add a simple firmware version check in my own code and set "this.useGetToPost =" accordingly.

I will report back if changing POST into GET does fix the issue for the 2018 model airco's, give me a couple of days as I have no access to a type B adapter my app users must try it for me.

**Comment by Apollon77** [comment]
Thank you! This help is appreciated because I also have no ccess to a model B wifi controller :-(

When you verified it send me a refernce to your check and I could also think about taking such a check in the library itself ... or you send a PR if you like :-)
For me it was too less/undetailed information so far to build it in

**Comment by PeterEIER** [comment]
Hi Ingo,

one of my app user lend me his type B adapter which I received today... with the type B adapter in my Emura 2 I can indeed replicate the issue... with my type A adapter I use POST to change settings when install the type B adapter POST does not work I must use GET to change settings. 

Conclusion: the type B adapter with firmware v1.2.48 requires that GET iso POST is used to change settings.

I simply added a checkbox to my app settings page... making decisions about the use of POST or GET based on either model or firmware version is tricky as Daikin can change the type B adapter firmware tomorrow and then what...

I would suggest that a simple comment in the readme.MD of your Daikin-Controller app about this type B adapters behaviour should be sufficient. For me personally you don't have to change your code...

**Comment by Apollon77** [comment]
Thank you for your information.

I enhanced the README: https://github.com/Apollon77/daikin-controller/commit/70a2957ed9ab988b9c783d2afb890a6461ea3c97
