### ISSUE TITLE
Question: setACSpecialMode

### ISSUE THREAD

**Issue by DIY-Blub** [Apollon77/daikin-controller#70]
Hallo,
kannst Du bitte ein Beispiel zu "setACSpecialMode" posten? Also wie man den Streamer aktiviert oder den Powerful-Modus aktiviert? Ich komm mit der Syntax leider nicht klar :(
Schöne Grüße

**Comment by Apollon77** [comment]
https://github.com/Apollon77/ioBroker.daikin/blob/master/daikin.js#L305

**Comment by DIY-Blub** [comment]
Danke
