### ISSUE TITLE
Functions: Komfort & Intelligentes Auge

### ISSUE THREAD

**Issue by DIY-Blub** [Apollon77/daikin-controller#71]
**Is your feature request related to a problem? Please describe.**
The AC device offers further functions, which I would like to control with this repo.

**Describe the solution you'd like**
Enable and disable the following functions:
Komfort: _Automatisch die Luftstromrichtung anpassen, um den Raum effizienter zu heizen oder zu kühlen ("Coandă-Effekt")._
Intelligentes Auge: _Verhindern, dass der Luftstrom direkt auf Personen gerichtet ist. Strom sparen, wenn niemand im Raum ist. (Personenerkennung)_

**Describe alternatives you've considered**
Functions can only be used on the infrared remote control. :(

**Additional context**
-

**Comment by Apollon77** [comment]
Yes, the API does not seem to offer this right now ... (or is it possible for you via the mobile app?) ... so as soon as noone finds the connected API methods it stays that way :-(

**Comment by DIY-Blub** [comment]
The mobile app doesn't offer the ECONO mode, but this is selectable in this repo :D

**Comment by Apollon77** [comment]
because someone found it in the api :-)
