### ISSUE TITLE
lpw parameter ? (Question about release v1.2.0)

### ISSUE THREAD

**Issue by DIY-Blub** [Apollon77/daikin-controller#91]
In the release v1.2.0 the lpw parameter was added. What does lpw stand for or, if it is not clear from the context, what can be done with the parameter?

**Comment by Apollon77** [comment]
It seemed that some devices needs that as kind of new security featute from Daikin ... in the end it was never proofed if really the case or not, but it also should be "under the hood" ... so when it is set in one place in settings it is added to some requests ... also other libraries are doing it that way.

So in fact we will leave as is until something do not work with it :-)
