### ISSUE TITLE
Daikin Airco in Node Red

### ISSUE THREAD

**Issue by LucSieben** [Apollon77/daikin-controller#96]
Hi,

I am really new with Node Red and had a question about a connection.
For a project i must connect the Daikin Airco with Node-Red or Ignition (Inductive Automation). I have 2 things the airco and a Touch manager,

Intelligent Touch Manager
Ver 1.27.00

and airco,
RXYQ14U7Y1B

is there a possibilty to connect this? I can't find any DeviceID only a IP adress.

Kind regrats,

Luc Sieben

**Comment by Apollon77** [comment]
I'm not aware of any node-red nodes for daikin ... But in general pot yes someone could write that based on my library -... But I can not help here right now. Also No idea what a Touch manager" is
