### ISSUE TITLE
Support for FVXM25A Air Conditioner with integrated WIFI

### ISSUE THREAD

**Issue by dhermanns** [Apollon77/daikin-controller#97]
Should the above 2020 Model above work with your library?

If not - any idea where I find some informations about it's HTTP-API?

**Comment by Apollon77** [comment]
It all depends on the used Wifi Adapter tye ... if it is one of the listed ones from readme ll is good, if it is the "new" cloud based BRP069C4x adapter then we currently discuss options at https://github.com/cbrandlehner/homebridge-daikin-local/issues/123 ... there in fact is no HTTP API

So which wifi adapter is it?

**Comment by dhermanns** [comment]
Not sure - since it is an internal Wifi Adapter. Does the cloud based adapter is controlled by the residential daikin app? Then it's indeed the new one :-/

**Comment by dhermanns** [comment]
Ah ok - read your linked issue.
Sounds like mine is BRP069C4x, too. But reads promising the we will have a way to connect soon.

**Comment by Apollon77** [comment]
Hopefully yes :-)
